source 'http://rubygems.org'

gem 'rails', '~>3.0.3'
gem 'mysql2', '~>0.2.7'
#gem 'ruby-debug'
gem 'acts_as_list'
gem 'less'
gem 'factory_girl'
gem 'validate_email'
gem 'hoptoad_notifier'

# required for common_engine
gem 'acts_as_state_machine'
gem 'activerecord-oracle_enhanced-adapter', '1.3.2'
gem 'ruby-oci8'
gem 'paperclip'
gem 'dalli'
gem 'liquid'
gem 'aws-s3'
gem 'rack-contrib' 